In [1]:
import pandas as pd

images = pd.read_csv('C:/Users/s_csmscox/jupyterSave/kFashion/kaggle_fashion/images.csv')
styles = pd.read_csv('C:/Users/s_csmscox/jupyterSave/kFashion/kaggle_fashion/styles.csv')

In [3]:
import numpy as np

sub = styles['subCategory']
uni = sub.unique()

In [4]:
cnt = []
product = []

for i in uni:
    cnt.append(0)
    product.append(i)

a = -1

for i in uni:
    a += 1
    for j in sub:
        if i == j:
            cnt[a] += 1

In [5]:
df1 = pd.DataFrame(product, columns=['product'])
df2 = pd.DataFrame(cnt, columns=['cnt'])

df = pd.concat([df1, df2], axis=1)
df.sort_values(by=['cnt'], axis=0, inplace=True,  ascending=False)
df

                     product    cnt
0                    Topwear  15405
4                      Shoes   7344
7                       Bags   3055
1                 Bottomwear   2694
2                    Watches   2542
8                  Innerwear   1808
12                 Jewellery   1080
15                   Eyewear   1073
11                 Fragrance   1012
9                     Sandal    963
20                   Wallets    933
6                 Flip Flops    915
5                      Belts    811
3                      Socks    698
13                      Lips    527
18                     Dress    478
19  Loungewear and Nightwear    470
14                     Saree    427
16                     Nails    329
25                    Makeup    307
22                  Headwear    293
27                      Ties    258
28               Accessories    143
17                   Scarves    118
36                 Cufflinks    108
21               Apparel Set    106
26                Free Gifts    104
38                    Stoles     90
24                 Skin Care     77
29                      Skin     69
32                      Eyes     43
23                  Mufflers     38
10          Shoe Accessories     24
37          Sports Equipment     21
34                    Gloves     20
39                      Hair     19
33             Bath and Body     12
31              Water Bottle      7
40                  Perfumes      6
42                 Umbrellas      6
30        Beauty Accessories      4
43                Wristbands      4
35        Sports Accessories      3
41           Home Furnishing      1
44                  Vouchers      1

In [26]:
data = styles.loc[(styles['subCategory'] == 'Topwear') |
                  (styles['subCategory'] == 'Bottomwear') |
                  (styles['subCategory'] == 'Shoes') |
                  (styles['subCategory'] == 'Bags') |
                  (styles['subCategory'] == 'Watches') |
                  (styles['subCategory'] == 'Innerwear'),['id', 'subCategory']]
data

          id subCategory
0      15970     Topwear
1      39386  Bottomwear
2      59263     Watches
3      21379  Bottomwear
4      53759     Topwear
...      ...         ...
44439  12544     Topwear
44440  42234     Topwear
44441  17036       Shoes
44443  18842     Topwear
44445  51623     Watches

[32848 rows x 2 columns]

In [27]:
data['subCategory'].loc[data['subCategory'] == 'Topwear'] = 0
data['subCategory'].loc[data['subCategory'] == 'Bottomwear'] = 1
data['subCategory'].loc[data['subCategory'] == 'Shoes'] = 2
data['subCategory'].loc[data['subCategory'] == 'Bags'] = 3
data['subCategory'].loc[data['subCategory'] == 'Watches'] = 4
data['subCategory'].loc[data['subCategory'] == 'Innerwear'] = 5
data

C:\Users\s_csmscox\Anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)

          id subCategory
0      15970           0
1      39386           1
2      59263           4
3      21379           1
4      53759           0
...      ...         ...
44439  12544           0
44440  42234           0
44441  17036           2
44443  18842           0
44445  51623           4

[32848 rows x 2 columns]

In [28]:
import shutil

dst = 'C:/Users/s_csmscox/jupyterSave/kFashion/kaggle_fashion/train/'

for file_name, category_id in zip(data['id'],data['subCategory']):
    src = 'C:/Users/s_csmscox/jupyterSave/kFashion/kaggle_fashion/images/'+str(file_name)+'.jpg'
    try:
        shutil.copy(src, (dst + str(category_id ) + '/'))
    except:
        pass

In [39]:
import shutil
from sklearn.model_selection import train_test_split

Topwear = data.loc[data['subCategory']==0, :]

Topwear_train, Topwear_test = train_test_split(Topwear, test_size=0.2, random_state=42)
Topwear_train, Topwear_valid = train_test_split(Topwear_train, test_size=0.2, random_state=42)

dst = 'C:/Users/s_csmscox/jupyterSave/kFashion/kaggle_fashion/train/'

for file_name, category_id in zip(Topwear_train['id'],Topwear_train['subCategory']):
    src = 'C:/Users/s_csmscox/jupyterSave/kFashion/kaggle_fashion/images/'+str(file_name)+'.jpg'
    try:
        shutil.copy(src, (dst + str(category_id ) + '/'))
    except:
        pass
    
dst = 'C:/Users/s_csmscox/jupyterSave/kFashion/kaggle_fashion/test/'

for file_name, category_id in zip(Topwear_test['id'],Topwear_test['subCategory']):
    src = 'C:/Users/s_csmscox/jupyterSave/kFashion/kaggle_fashion/images/'+str(file_name)+'.jpg'
    try:
        shutil.copy(src, (dst + str(category_id ) + '/'))
    except:
        pass
    
dst = 'C:/Users/s_csmscox/jupyterSave/kFashion/kaggle_fashion/valid/'

for file_name, category_id in zip(Topwear_valid['id'],Topwear_valid['subCategory']):
    src = 'C:/Users/s_csmscox/jupyterSave/kFashion/kaggle_fashion/images/'+str(file_name)+'.jpg'
    try:
        shutil.copy(src, (dst + str(category_id ) + '/'))
    except:
        pass

In [41]:
Bottomwear = data.loc[data['subCategory']==1, :]

Bottomwear_train, Bottomwear_test = train_test_split(Bottomwear, test_size=0.2, random_state=42)
Bottomwear_train, Bottomwear_valid = train_test_split(Bottomwear_train, test_size=0.2, random_state=42)

dst = 'C:/Users/s_csmscox/jupyterSave/kFashion/kaggle_fashion/train/'

for file_name, category_id in zip(Bottomwear_train['id'],Bottomwear_train['subCategory']):
    src = 'C:/Users/s_csmscox/jupyterSave/kFashion/kaggle_fashion/images/'+str(file_name)+'.jpg'
    try:
        shutil.copy(src, (dst + str(category_id ) + '/'))
    except:
        pass
    
dst = 'C:/Users/s_csmscox/jupyterSave/kFashion/kaggle_fashion/test/'

for file_name, category_id in zip(Bottomwear_test['id'],Bottomwear_test['subCategory']):
    src = 'C:/Users/s_csmscox/jupyterSave/kFashion/kaggle_fashion/images/'+str(file_name)+'.jpg'
    try:
        shutil.copy(src, (dst + str(category_id ) + '/'))
    except:
        pass
    
dst = 'C:/Users/s_csmscox/jupyterSave/kFashion/kaggle_fashion/valid/'

for file_name, category_id in zip(Bottomwear_valid['id'],Bottomwear_valid['subCategory']):
    src = 'C:/Users/s_csmscox/jupyterSave/kFashion/kaggle_fashion/images/'+str(file_name)+'.jpg'
    try:
        shutil.copy(src, (dst + str(category_id ) + '/'))
    except:
        pass

In [42]:
Shoes = data.loc[data['subCategory']==2, :]

Shoes_train, Shoes_test = train_test_split(Shoes, test_size=0.2, random_state=42)
Shoes_train, Shoes_valid = train_test_split(Shoes_train, test_size=0.2, random_state=42)

dst = 'C:/Users/s_csmscox/jupyterSave/kFashion/kaggle_fashion/train/'

for file_name, category_id in zip(Shoes_train['id'],Shoes_train['subCategory']):
    src = 'C:/Users/s_csmscox/jupyterSave/kFashion/kaggle_fashion/images/'+str(file_name)+'.jpg'
    try:
        shutil.copy(src, (dst + str(category_id ) + '/'))
    except:
        pass
    
dst = 'C:/Users/s_csmscox/jupyterSave/kFashion/kaggle_fashion/test/'

for file_name, category_id in zip(Shoes_test['id'],Shoes_test['subCategory']):
    src = 'C:/Users/s_csmscox/jupyterSave/kFashion/kaggle_fashion/images/'+str(file_name)+'.jpg'
    try:
        shutil.copy(src, (dst + str(category_id ) + '/'))
    except:
        pass
    
dst = 'C:/Users/s_csmscox/jupyterSave/kFashion/kaggle_fashion/valid/'

for file_name, category_id in zip(Shoes_valid['id'],Shoes_valid['subCategory']):
    src = 'C:/Users/s_csmscox/jupyterSave/kFashion/kaggle_fashion/images/'+str(file_name)+'.jpg'
    try:
        shutil.copy(src, (dst + str(category_id ) + '/'))
    except:
        pass

In [43]:
Bags = data.loc[data['subCategory']==3, :]

Bags_train, Bags_test = train_test_split(Bags, test_size=0.2, random_state=42)
Bags_train, Bags_valid = train_test_split(Bags_train, test_size=0.2, random_state=42)

dst = 'C:/Users/s_csmscox/jupyterSave/kFashion/kaggle_fashion/train/'

for file_name, category_id in zip(Bags_train['id'],Bags_train['subCategory']):
    src = 'C:/Users/s_csmscox/jupyterSave/kFashion/kaggle_fashion/images/'+str(file_name)+'.jpg'
    try:
        shutil.copy(src, (dst + str(category_id ) + '/'))
    except:
        pass
    
dst = 'C:/Users/s_csmscox/jupyterSave/kFashion/kaggle_fashion/test/'

for file_name, category_id in zip(Bags_test['id'],Bags_test['subCategory']):
    src = 'C:/Users/s_csmscox/jupyterSave/kFashion/kaggle_fashion/images/'+str(file_name)+'.jpg'
    try:
        shutil.copy(src, (dst + str(category_id ) + '/'))
    except:
        pass
    
dst = 'C:/Users/s_csmscox/jupyterSave/kFashion/kaggle_fashion/valid/'

for file_name, category_id in zip(Bags_valid['id'],Bags_valid['subCategory']):
    src = 'C:/Users/s_csmscox/jupyterSave/kFashion/kaggle_fashion/images/'+str(file_name)+'.jpg'
    try:
        shutil.copy(src, (dst + str(category_id ) + '/'))
    except:
        pass

In [44]:
Watches = data.loc[data['subCategory']==4, :]

Watches_train, Watches_test = train_test_split(Watches, test_size=0.2, random_state=42)
Watches_train, Watches_valid = train_test_split(Watches_train, test_size=0.2, random_state=42)

dst = 'C:/Users/s_csmscox/jupyterSave/kFashion/kaggle_fashion/train/'

for file_name, category_id in zip(Watches_train['id'],Watches_train['subCategory']):
    src = 'C:/Users/s_csmscox/jupyterSave/kFashion/kaggle_fashion/images/'+str(file_name)+'.jpg'
    try:
        shutil.copy(src, (dst + str(category_id ) + '/'))
    except:
        pass
    
dst = 'C:/Users/s_csmscox/jupyterSave/kFashion/kaggle_fashion/test/'

for file_name, category_id in zip(Watches_test['id'],Watches_test['subCategory']):
    src = 'C:/Users/s_csmscox/jupyterSave/kFashion/kaggle_fashion/images/'+str(file_name)+'.jpg'
    try:
        shutil.copy(src, (dst + str(category_id ) + '/'))
    except:
        pass
    
dst = 'C:/Users/s_csmscox/jupyterSave/kFashion/kaggle_fashion/valid/'

for file_name, category_id in zip(Watches_valid['id'],Watches_valid['subCategory']):
    src = 'C:/Users/s_csmscox/jupyterSave/kFashion/kaggle_fashion/images/'+str(file_name)+'.jpg'
    try:
        shutil.copy(src, (dst + str(category_id ) + '/'))
    except:
        pass

In [45]:
Innerwear = data.loc[data['subCategory']==5, :]

Innerwear_train, Innerwear_test = train_test_split(Innerwear, test_size=0.2, random_state=42)
Innerwear_train, Innerwear_valid = train_test_split(Innerwear_train, test_size=0.2, random_state=42)

dst = 'C:/Users/s_csmscox/jupyterSave/kFashion/kaggle_fashion/train/'

for file_name, category_id in zip(Innerwear_train['id'],Innerwear_train['subCategory']):
    src = 'C:/Users/s_csmscox/jupyterSave/kFashion/kaggle_fashion/images/'+str(file_name)+'.jpg'
    try:
        shutil.copy(src, (dst + str(category_id ) + '/'))
    except:
        pass
    
dst = 'C:/Users/s_csmscox/jupyterSave/kFashion/kaggle_fashion/test/'

for file_name, category_id in zip(Innerwear_test['id'],Innerwear_test['subCategory']):
    src = 'C:/Users/s_csmscox/jupyterSave/kFashion/kaggle_fashion/images/'+str(file_name)+'.jpg'
    try:
        shutil.copy(src, (dst + str(category_id ) + '/'))
    except:
        pass
    
dst = 'C:/Users/s_csmscox/jupyterSave/kFashion/kaggle_fashion/valid/'

for file_name, category_id in zip(Innerwear_valid['id'],Innerwear_valid['subCategory']):
    src = 'C:/Users/s_csmscox/jupyterSave/kFashion/kaggle_fashion/images/'+str(file_name)+'.jpg'
    try:
        shutil.copy(src, (dst + str(category_id ) + '/'))
    except:
        pass